name: czech-weather

services:
  database:
    image: postgres:17-alpine
    container_name: czech-weather-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=czech_weather
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s
    ports:
      - "5432:5432"
